apiVersion: apps/v1
kind: Deployment
metadata:
  name: article-service
  namespace: production
  labels:
    app: article-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: article-service
  template:
    metadata:
      labels:
        app: article-service
    spec:
      initContainers:
        - name: wait-for-dependencies
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              until nc -z article-db 5432; do echo waiting for article-db; sleep 2; done
              until nc -z eureka-server 8761; do echo waiting for eureka-server; sleep 2; done
      containers:
        - name: article-service
          image: khanhduy05/article-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9003
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "700m"
              memory: "1Gi"
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 9003
            failureThreshold: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 9003
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 9003
            initialDelaySeconds: 60
            periodSeconds: 20
