apiVersion: v1
kind: Service
metadata:
  name: article-service
  namespace: production
  labels:
    app: article-service
spec:
  selector:
    app: article-service
  ports:
    - protocol: TCP
      port: 9003
      targetPort: 9003
  type: ClusterIP
