apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: production
  labels:
    app: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: khanhduy05/api-gateway:58
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: AUTH_SERVICE_URL
              value: http://auth-service:9001
            - name: USER_SERVICE_URL
              value: http://user-service:9002
            - name: ARTICLE_SERVICE_URL
              value: http://article-service:9003
            - name: COMMENT_SERVICE_URL
              value: http://comment-service:9004
            - name: SPRING_CLOUD_DISCOVERY_ENABLED
              value: "false"
            - name: EUREKA_CLIENT_ENABLED
              value: "false"
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "300m"
              memory: "512Mi"
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            failureThreshold: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 20
