pipeline {
    agent any

    environment {
        GITHUB_REPO      = 'https://github.com/vominhduong/blogApp_cicd.git'
        BRANCH_NAME      = 'main'
        SERVICE_NAME     = 'comment-service'
        SERVICE_PATH     = 'backend/comment-service'
        GRADLE_MODULE    = ':backend:comment-service'
        DOCKER_IMAGE     = 'khanhduy05/comment-service'
        DOCKER_TAG       = "${BUILD_NUMBER}"
        SONARQUBE_SERVER = 'SonarQube'
    }

    stages {

        stage('Checkout Code') {
            steps {
                echo '========== Checkout Code =========='
                git branch: "${BRANCH_NAME}", url: "${GITHUB_REPO}"
                sh 'chmod +x gradlew'
            }
        }

        stage('Build Service') {
            steps {
                echo '========== Build API Gateway =========='
                sh "./gradlew ${GRADLE_MODULE}:clean ${GRADLE_MODULE}:build"
            }
        }

        stage('Check Build Output') {
            steps {
                echo '========== Check JAR =========='
                sh "ls -lah backend/${SERVICE_NAME}/build/libs/"
            }
        }

        stage('SonarQube Analysis') {
            steps {
                echo '========== SonarQube Analysis =========='
                withSonarQubeEnv("${SONARQUBE_SERVER}") {
                    sh "./gradlew sonarqube"
                }
            }
        }

        stage('Quality Gate') {
            steps {
                timeout(time: 5, unit: 'MINUTES') {
                    waitForQualityGate abortPipeline: true
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                echo '========== Build Docker Image =========='
                
                dir("${SERVICE_PATH}") {
                    sh """
                        docker build -t ${DOCKER_IMAGE}:${DOCKER_TAG} .
                        
                        docker tag ${DOCKER_IMAGE}:${DOCKER_TAG} ${DOCKER_IMAGE}:latest
                    """
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                echo '========== Push Docker Image =========='
                withDockerRegistry([credentialsId: 'dockerhub', url: 'https://index.docker.io/v1/']) {
                    sh """
                        docker push ${DOCKER_IMAGE}:${DOCKER_TAG}
                        docker push ${DOCKER_IMAGE}:latest
                    """
                }
            }
        }
    }

    post {
        always {
            echo '========== Pipeline Finished =========='
            cleanWs()
        }
        success {
            echo 'Pipeline executed successfully'
        }
        failure {
            echo 'Pipeline failed - Check logs for details'
        }
    }
}
