apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: production
  labels:
    app: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      initContainers:
        - name: wait-for-dependencies
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              until nc -z user-db 5432; do echo waiting for user-db; sleep 2; done
      containers:
        - name: user-service
          image: khanhduy05/user-service:39
          imagePullPolicy: Always
          ports:
            - containerPort: 9002
          env:
            - name: SPRING_APPLICATION_NAME
              value: user-service
            - name: K8S_SERVICE_DNS
              value: user-service
            - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
              value: http://eureka-server:8761/eureka/
            - name: EUREKA_CLIENT_REGISTER_WITH_EUREKA
              value: "true"
            - name: EUREKA_CLIENT_FETCH_REGISTRY
              value: "true"
            - name: SPRING_CLOUD_DISCOVERY_ENABLED
              value: "true"
            - name: EUREKA_CLIENT_ENABLED
              value: "true"
          resources:
            requests:
              cpu: "150m"
              memory: "256Mi"
            limits:
              cpu: "400m"
              memory: "512Mi"
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 9002
            failureThreshold: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 9002
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 9002
            initialDelaySeconds: 60
            periodSeconds: 20
