spring.application.name=article-service
server.port=9003

# Register with Eureka Server
eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://eureka-server:8761/eureka/}
eureka.instance.prefer-ip-address=false
eureka.instance.hostname=${K8S_SERVICE_DNS:${HOSTNAME:${spring.application.name}}}
eureka.instance.non-secure-port=${server.port}
eureka.instance.instance-id=${spring.application.name}:${POD_NAME:${HOSTNAME:${random.value}}}

spring.datasource.driver-class-name = org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://article-db:5432/articledb
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update

# Actuator for Docker healthcheck
management.endpoint.health.show-details=always
management.endpoints.web.exposure.include=health,info
